#!/bin/bash -l
# Batch processing script


#PBS -l nodes=1:ppn=4,walltime=23:45:00
#PBS -N 3DSoft-1000



# Load required modules (compiler, ...)
module load python/3.7-anaconda
module load cuda/10.0
module load cmake/3.11.1
# Activate local environment where hoomd is installed
source activate localconda

# change to temporary job data directory
# located in node, between 400-900GB
cd  $WORK

# run simulation
python ~/MasterThesis/Code/Gnan_Parameter_Histeresis3DSoft.py -n 32 -k 1000

