#!/bin/bash -l
# Batch processing script


#PBS -l nodes=1:ppn=4,walltime=00:30:00
#PBS -N rigidHoomd



# Load required modules (compiler, ...)
module load python/3.7-anaconda
module load cuda/10.0
module load cmake/3.11.1
# Activate local environment where hoomd is installed
source activate localconda

# change to temporary job data directory
# located in node, between 400-900GB
cd  $WORK

# run simulation
python $HOME/MasterThesis/Code/Marson_Parameter_HisteresisOne.py &

wait
